
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置数据库
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root